# 실레나 좌표
RARENA_WIDTH = 95
RARENA_HEIGHT = 57
RARENA_DY = 11

RARENA_START_X1 = 315
RARENA_END_X1 = RARENA_START_X1 + RARENA_WIDTH

RARENA_START_X2 = 810
RARENA_END_X2 = RARENA_START_X2 + RARENA_WIDTH

RARENA_START_Y1 = 178
RARENA_END_Y1 = RARENA_START_Y1 + RARENA_HEIGHT

RARENA_START_Y2 = RARENA_END_Y1 + RARENA_DY
RARENA_END_Y2 = RARENA_START_Y2 + RARENA_HEIGHT

RARENA_START_Y3 = RARENA_END_Y2 + RARENA_DY
RARENA_END_Y3 = RARENA_START_Y3 + RARENA_HEIGHT

RARENA_START_Y4 = RARENA_END_Y3 + RARENA_DY
RARENA_END_Y4 = RARENA_START_Y4 + RARENA_HEIGHT

RARENA_START_Y5 = RARENA_END_Y4 + RARENA_DY
RARENA_END_Y5 = RARENA_START_Y5 + RARENA_HEIGHT